chore(deps): Replace react-truncate with FEC Truncate
RedHatInsights/compliance-frontend pull request #1352
Opened 2021-08-25 09:50 UTC by bastilian

This replaces the outdated react-truncate with the `Truncate` component provided by frontend-components:

![Screenshot 2021-08-25 at 11 47 34](https://user-images.githubusercontent.com/7757/130769112-949d6686-3b0e-4308-9099-642b73c75e47.png)
![Screenshot 2021-08-25 at 11 47 14](https://user-images.githubusercontent.com/7757/130769120-62777797-a8cb-441c-8342-03de73cee521.png)

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-08-25 09:54 UTC, bastilian commented
@katierik This is replacing the way we truncate text, with a component provided by the platform. However this changes some minor things. Mainly instead of just cutting off the text, it will actually add a "Read more" link. Is this OK, or should we extend the platform component to support the way we are currently cutting text?

2021-08-30 19:57 UTC, katierik commented
@bastilian Adding a "read more" is great. 👍

2021-09-02 18:14 UTC, akofink reviewed
Thanks, @bastilian! Just a few questions inline

2021-09-02 18:14 UTC, akofink commented on src/PresentationalComponents/SystemPolicyCard/SystemPolicyCard.js
> +
:thinking: so there are cases where we don't want a 'Read more' and instead want this mouseover functionality - I feel like we should extend the Truncate component to allow for that case?

2021-09-02 18:14 UTC, akofink commented on src/SmartComponents/SystemsTable/Cells.js
> +);
Nit: we don't need Truncate at all if policies are null/empty.

2021-09-02 18:14 UTC, akofink commented on src/SmartComponents/SystemsTable/Cells.js
> +    lenght={100}
```suggestion
    length={100}
```

2021-09-02 18:14 UTC, akofink commented
I'd also nitpick about this being a 'chore' since it's changing behavior from mouseover to 'read more' in at least one place.

2021-09-02 20:24 UTC, bastilian commented on src/PresentationalComponents/SystemPolicyCard/SystemPolicyCard.js
> +
Yes, I think, we can open a PR and add that functionality there. I haven't done that yet, because it also requires the mouse-over and out behaviour to be implemented, for this use-case here.

2021-09-02 20:27 UTC, bastilian commented
@akofink I just picked "chore" because that is what I mostly use for package updates, I can change it. :) However, I did not intend to change that behaviour. I must have overlooked that. I'll check again and fix that.

2021-09-02 21:16 UTC, akofink commented on src/PresentationalComponents/SystemPolicyCard/SystemPolicyCard.js
> +
:+1: we can definitely do it after this PR, but it caught my eye that we're using this new Truncate component but also having to define a custom `truncate` function! :laughing:

2021-09-03 08:44 UTC, bastilian commented
@akofink I checked that changes, I couldn't find the place you mention where we chance from mouse over to "read me". The only place where anything happens on mouseover, which is already the case in master. The places where we do add a "Read me" are all "on click" and are confirmed above with UX.

2021-09-16 19:06 UTC, akofink approved these changes
Works as expected. Thanks!

2021-09-16 19:18 UTC, akofink requested changes
Actually, this seems to break the system details page for unsupported systems. The test failure pointed me towards the scenario, and it definitely also fails in the UI. Unfortunately, I'm unsure what the issue is - it's still wrapped inside a minified react error :confused: How do you see the actual trace?

2021-09-16 19:49 UTC, bastilian commented
@akofink It was probably missing the latest changes from master. It was still showing the "Update branch" button. I just rebased the commits again on top of the latest master again.

2021-09-16 20:05 UTC, akofink approved these changes
Thanks, @bastilian! Not sure why my rebase wasn't correct :thinking: :laughing: Works as expected!

2021-09-16 20:05 UTC, merged