feat(CreatePolicy): RHICOMPL-2400 Update create policy form to use th…
RedHatInsights/compliance-frontend pull request #1498
Opened 2021-12-08 20:31 UTC by marleystipich2

…e GQL end point for all supported profiles

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-12-08 20:36 UTC, skateman requested changes

2021-12-08 20:36 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      latestBenchmarks {
You won't need this, all the data can be loaded via the query you're adding.

2021-12-08 20:36 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +            complianceThreshold
You can also load the benchmark version here as I have it in the issue in the sample query.

2021-12-08 20:36 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +    BENCHMARKS_AND_PROFILES_AND_OS_MAJOR_VERSIONS,
`SUPPORTED_PROFILES_BY_OS_MAJOR`

2021-12-08 20:40 UTC, marleystipich2 commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +            complianceThreshold
Okay, yeah I did have it in there but I removed it because I wasn't using it but I'll add it back in there in case we ned it for something

2021-12-08 20:53 UTC, marleystipich2 commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      latestBenchmarks {
Sorry, which part isn't needed? Do you mean I can load all of the benchmark data in the osMajorVersions query?

2021-12-08 21:12 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      latestBenchmarks {
Yes, you only need the benchmark version I believe and that's possible different for each profile. Part of the data coming from this query is obsolete (latest benchmarks) and the rest is a partial duplicate (latest profiles).

2021-12-08 21:12 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +            complianceThreshold
You need it, because the version for each profile might be different...

2021-12-09 04:39 UTC, marleystipich2 commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      latestBenchmarks {
Okay, yeah I see what you mean now. The only part I'm confused about is that latestBenchmark is still being used like this:
```
const benchmarks = data.latestBenchmarks;
...
 if (selectedBenchmarkId) {
    selectedBenchmark = benchmarks.find(
      (benchmark) => benchmark.id === selectedBenchmarkId
    );
```
Is there a way I can find the `selectedBenchmark` without latestBenchmark?

2021-12-09 09:00 UTC, bastilian commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +      osMajorVersions.filter(
You can use `.find` here and avoid the `[0]`.

2021-12-09 10:28 UTC, vkrizan commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +      osMajorVersions.filter(
... and please add safe navigation if the item isn't found or treat it other way. :slightly_smiling_face:

2021-12-09 10:29 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      latestBenchmarks {
Yeah, the `selectedBenchmark` should come from under the (selected) profile, as it can be different for each.

2021-12-09 13:46 UTC, marleystipich2 commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      latestBenchmarks {
Oh okay that makes more sense. I'll work on that now!

2021-12-09 22:04 UTC, marleystipich2 commented
@bastilian Can you take a look at this, when you get a chance? I made some updates that were needed but now, when I select an OS version and then a profile, the "Next" button stays disabled. So it seems like it thinks the form isn't fully filled out but I'm not sure why?

2021-12-10 06:42 UTC, skateman commented
@marleystipich2 you need to make [this](https://github.com/RedHatInsights/compliance-frontend/blob/master/src/SmartComponents/CreatePolicy/CreatePolicy.js#L55) condition pass in order to enable the next button, it's defined [here](https://github.com/RedHatInsights/compliance-frontend/blob/master/src/SmartComponents/CreatePolicy/validate.js#L1-L7)

2021-12-10 13:33 UTC, marleystipich2 commented
@skateman Oh that helps a lot. Thanks!

2021-12-13 13:37 UTC, skateman commented
@marleystipich2 can you please address the issues in travis?

2021-12-13 22:14 UTC, marleystipich2 commented
@skateman Okay, I fixed the failing tests. Let me know if everything looks good to you!

2021-12-14 07:37 UTC, skateman commented on src/__fixtures__/benchmarks_rules.js
> +
Not sure if the file is generated or not, but a newline is missing :thinking:

2021-12-14 09:38 UTC, skateman commented
The code looks good, but there's a backend issue we need to address before merging :disappointed: profiles with different `ref_ids` but the same name showed up in the UI :disappointed: maybe we need to rely on the profiles in the supported SSG yaml file as you originally implemented the backend part :shrug: 

@bastilian can you please take a look at this? The code is okay, just want to hold this off until the backend issue is resolved.

2021-12-14 11:07 UTC, bastilian commented on src/__fixtures__/benchmarks_rules.js
> +
... I'd handy if we could generated these. ;)

2021-12-14 11:15 UTC, skateman commented on src/__fixtures__/benchmarks_rules.js
> +
In this case @marleystipich2 this needs an additional newline :wink:

2021-12-14 12:27 UTC, bastilian commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      selectedBenchmarkId: selector(state, 'benchmark'),
The `selectedBenchmarkId` could probably be removed. It seems to only occur here.

2021-12-14 13:07 UTC, bastilian commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +                  key={os.node.osMajorVersion}
This could also be `osMajorVersion`.

2021-12-14 13:11 UTC, bastilian commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
> +  const osMajorVersions = data.osMajorVersions?.edges;
Nice! Maybe we can (in the future) phase out the term "benchmark" completely (from the UI at least).

2021-12-14 13:55 UTC, marleystipich2 commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      selectedBenchmarkId: selector(state, 'benchmark'),
I tried removing this originally but `BenchmarkId` is still being used on the Review tab and it was getting it's value from this so when I removed this, the Review tab wasn't working.. Maybe that could be part of phasing out the term "benchmark"? Getting the Review tab to work correctly without `BenchmarkId`?

2021-12-14 13:58 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      selectedBenchmarkId: selector(state, 'benchmark'),
You can substitute the data coming from the new GQL request, the `benchmarkId` is no longer valid here anyway. Again, referring to the example query in the jira ticket :wink:

2021-12-14 14:13 UTC, marleystipich2 commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      selectedBenchmarkId: selector(state, 'benchmark'),
So use benchmark `version` instead? And update the Review page to take the benchmark version instead of id?

2021-12-14 14:20 UTC, skateman commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
>      selectedBenchmarkId: selector(state, 'benchmark'),
I don't know for what this data is being used for, but you can query the ID of the benchmark in GQL under each profile if it's necessary.

2022-01-13 07:58 UTC, bastilian commented
> @bastilian can you please take a look at this? The code is okay, just want to hold this off until the backend issue is resolved.

@skateman From my side this is PR is approved, is the issue in the backend resolved?

2022-01-13 08:01 UTC, skateman commented
@bastilian backend is fine, but we need a UX adjustment for this before merging. Katie started working on it after yesterday's meeting.

2022-02-10 02:10 UTC, bastilian commented
Closing this as the switch to this endpoint has been incorporated into https://github.com/RedHatInsights/compliance-frontend/pull/1518

2022-02-10 02:10 UTC, closed without merging