feat(ReportDetails): RHICOMPL-2548 - Include systems not reporting
RedHatInsights/compliance-frontend pull request #1509
Opened 2022-01-11 15:34 UTC by bastilian

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-01-25 06:14 UTC, skateman requested changes

2022-01-25 06:14 UTC, skateman commented on src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js
> +        ' compliant',
Can't we make these more readable with string interpolation?

2022-01-25 08:26 UTC, bastilian commented on src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js
> +        ' compliant',
Updated.

Usually these kind of nitpicks don't really justify a "requested change". Nitpick sure, but it shouldn't block a PR from being merged.

2022-01-26 07:37 UTC, skateman commented
Looks good, but I think I found another bug that will be more visible after merging this:
![Screenshot from 2022-01-26 08-36-43](https://user-images.githubusercontent.com/649130/151121972-1ef479fa-ab3a-40d2-b8f4-79411b6ab232.png)
I have 2 systems assigned to the policy, but I only see one here. I guess because only one is reporting. cc @LightOfHeaven1994

2022-01-26 07:39 UTC, skateman commented on src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js
> +              ' systems are not reporting scan results. This may be because the system is disconnected, or the insights-client is not properly configured to use Compliance.',
Maybe we need singular/plural version here? system vs systems
Not sure if we do it across the product though, so just asking...

2022-01-26 13:22 UTC, bastilian commented
@skateman That is no bug, it is not intented to show those systems there at the moment. We can check with UX/PM, but the mockups do not suggest anything to implement on the Reports page for now.

2022-01-26 13:22 UTC, bastilian commented on src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js
> +              ' systems are not reporting scan results. This may be because the system is disconnected, or the insights-client is not properly configured to use Compliance.',
Nice catch! I added pluralising here.

2022-01-27 08:22 UTC, skateman approved these changes
![The Seal of Approval](http://www.skateman.eu/seal.jpg)

2022-01-27 09:41 UTC, merged