perf(GraphQL): RHICOMPL-2426 reduce the queries for systems resources
RedHatInsights/compliance-frontend pull request #1647
Opened 2022-04-29 08:06 UTC by skateman

* Renamed `GET_SYSTEMS_ONLY` to `GET_SYSTEMS_WITH_POLICIES` 
* Replaced `GET_SYSTEMS` in profile details page with `GET_SYSTEMS_WITH_POLICIES`
* Renamed `GET_SYSTEMS` to `GET_SYSTEMS_WITH_REPORTS`
* Replaced `GET_SYSTEMS_WITHOUT_FAILED_RULES` with `GET_SYSTEMS_WITH_POLICIES`
* Deleted the obsolete `GET_SYSTEMS_WITHOUT_FAILED_RULES`

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2022-05-03 05:37 UTC, skateman commented
@bastilian can you please take a look?

2022-05-03 10:21 UTC, bastilian commented on src/SmartComponents/PolicyDetails/PolicySystemsTab.js
> +    query={GET_SYSTEMS_WITH_PROFILES}
This should be `GET_SYSTEMS_WITH_PROFILES` as it requires the `testResultProfiles` to get the SSG version.

local vs. stage:
![Screenshot 2022-05-03 at 12 18 12](https://user-images.githubusercontent.com/7757/166437589-c387f988-b602-48e9-bf39-5a0388f37ca0.png)
:

2022-05-03 10:23 UTC, bastilian requested changes
Thank you! Awesome @skateman! LGTM, other than the one query on the Policy details.

2022-05-03 11:19 UTC, skateman commented on src/SmartComponents/PolicyDetails/PolicySystemsTab.js
> +    query={GET_SYSTEMS_WITH_PROFILES}
Okay, the naming is wrong and it should be `GET_SYSTEMS_WITH_POLICIES` and I guess here it should be `GET_SYSTEMS_WITH_REPORTS`.

2022-05-03 12:09 UTC, bastilian commented on src/SmartComponents/PolicyDetails/PolicySystemsTab.js
> +    query={GET_SYSTEMS_WITH_PROFILES}
🤦 oh, yeah. my tired eyes don't go well with copy&pasting. :D

2022-05-04 08:26 UTC, bastilian approved these changes
Thank you @skateman! All looks good now!

2022-05-06 13:41 UTC, merged