fix(EmptyStates): RHICOMPL-1795 fix empty states in tables
RedHatInsights/compliance-frontend pull request #1650
Opened 2022-04-29 14:02 UTC by xmicha82

Fix for some broken tables introduced in the previous PR (#1648)

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2022-04-29 15:12 UTC, skateman requested changes

2022-05-02 08:58 UTC, bastilian commented
@xmicha82 There is something fishy with this change. You should only need to pass in a component for the `emptyRows` component, and the table tools should wrap it into a "cells" object in the `useRowsBuilder` hook. The current `emptyRows` const[0] should be a function that has the component passed in. It could also have the columns or just the size passed in to determine the `colSpan`.

[0] https://github.com/RedHatInsights/compliance-frontend/blob/master/src/Utilities/hooks/useTableTools/useRowsBuilder.js#L8

2022-05-02 10:42 UTC, bastilian commented on src/Utilities/hooks/useTableTools/useTableTools.js
> +    emptyRows: options.tableProps?.emptyRows,
The `emptyRows` option should be passed in with the `TableToolsTable` via the object for the `options` prop.

2022-05-23 10:06 UTC, bastilian approved these changes
Awesome work @xmicha82! Thank you!

2022-05-23 10:15 UTC, merged