feat(ReportsTable): new compliance filters
RedHatInsights/compliance-frontend pull request #1725
Opened 2022-08-03 13:00 UTC by Fewwy

Two new Compliance filters for the Reports table

![image](https://user-images.githubusercontent.com/62722417/182613998-9d5659f9-5c2a-459f-87a4-015dbb36be99.png)

![image](https://user-images.githubusercontent.com/62722417/182614094-3585275c-c9d6-4822-a8b9-a677d5867d44.png)

2022-08-03 17:43 UTC, Victoremepunto commented
How did the commitlint task passed for this commit message ? :thinking: - there's no mention to the JIRA task

2022-08-04 05:30 UTC, skateman commented
> How did the commitlint task passed for this commit message ? thinking - there's no mention to the JIRA task

we don't require a JIRA ticket in the commit message, but it would be nice to have it here :see_no_evil:

2022-08-04 08:41 UTC, xmicha82 commented
hey, is this correct behaviour?
![image](https://user-images.githubusercontent.com/62351699/182803583-a3d8b1ec-f7fc-4e03-882c-5a790c1eb645.png)

2022-08-04 08:52 UTC, LightOfHeaven1994 commented
LGTM, thanks @Fewwy !

2022-08-04 08:54 UTC, LightOfHeaven1994 approved these changes

2022-08-04 09:33 UTC, LightOfHeaven1994 requested changes
![Screenshot from 2022-08-04 11-31-51](https://user-images.githubusercontent.com/33912805/182814532-9de367a1-c027-46a7-9343-949d9b884adc.png)
I was able to reproduce bug that Martin attached

2022-08-04 10:41 UTC, Fewwy commented
@LightOfHeaven1994 Ok I'm looking in to the why the bug is happening

2022-08-04 11:51 UTC, skateman commented
It might be a backend issue, I'm investigating.

2022-08-05 15:15 UTC, Fewwy commented
@skateman Any updates?

2022-08-19 12:01 UTC, skateman commented
I'm deep in debugging a memory leak and our SLO, so this has a lower prio atm.

2022-08-25 13:07 UTC, skateman reviewed
Not sure if UX would approve it, but I think we should restrict these filters a little bit. Ideally by allowing only one to be selected from these. Is that something doable? We're very limited here on the backend :disappointed:

2022-08-25 13:07 UTC, skateman commented on src/constants.js
> +      { label: 'Non-compliant', value: 'compliant = false' },
I think what @LightOfHeaven1994 is describing can be fixed by these changes:
```suggestion
      { label: 'Compliant', value: 'compliant = true AND supported_ssg = true' },
      { label: 'Non-compliant', value: 'compliant = false AND supported_ssg = true' },
```

2022-08-26 07:09 UTC, LightOfHeaven1994 commented on src/constants.js
> +      { label: 'Non-compliant', value: 'compliant = false' },
@Fewwy can you try David's suggestion? also PR needs to be rebased as we use new tags gql query

2022-08-26 07:13 UTC, skateman commented on src/constants.js
> +      { label: 'Non-compliant', value: 'compliant = false' },
@LightOfHeaven1994 he's on PTO, I rebased and adjusted the PR, can you please take a look?

2022-08-26 07:31 UTC, LightOfHeaven1994 commented on src/constants.js
> +      { label: 'Non-compliant', value: 'compliant = false' },
@skateman Works great now! thanks for the fix <3

2022-08-26 07:41 UTC, LightOfHeaven1994 approved these changes

2022-08-26 08:30 UTC, merged