chore(ssgVersion): RHICOMPL-3204 use only benchmark version as ssgVer…
RedHatInsights/compliance-frontend pull request #1740
Opened 2022-08-23 11:01 UTC by mkholjuraev

resolves: [RHICOMPL-3204](https://issues.redhat.com/browse/RHICOMPL-3204).

This PR modifies the code to only use the `benchmark.version` as `ssgVersion`. I have found some places where `ssgVersion` is not needed. I have removed fetching that info for those places.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-08-25 06:02 UTC, skateman requested changes
Looks good, but I'll need some explanation for certain locations and also I'd prefer to not rename results. Let's prefer `benchmark.version` over `.benchmark.ssgVersion` wherever we can.

2022-08-25 06:02 UTC, skateman commented on src/SmartComponents/ReportDownload/constants.js
> -        version
Aren't we losing information by dropping this one as well?

2022-08-25 06:02 UTC, skateman commented on src/SmartComponents/SystemDetails/ComplianceDetail.js
> -        ssgVersion
Is this query never consuming this information? Please clarify.

2022-08-25 06:02 UTC, skateman commented on src/SmartComponents/SystemsTable/constants.js
> +            benchmark {
This needs some performance testing, in cases like this when there are no benchmarks pulled into the query, it might be slower. Just please point me where it is being used in the FE.

2022-08-26 11:26 UTC, mkholjuraev commented on src/SmartComponents/SystemsTable/constants.js
> +            benchmark {
it is used [here](https://github.com/RedHatInsights/compliance-frontend/blob/master/src/SmartComponents/SystemsTable/Cells.js#L89)

2022-08-26 11:27 UTC, mkholjuraev commented on src/SmartComponents/EditPolicy/EditPolicy.js
> +            ssgVersion: version
I have undone all renamings

2022-08-26 11:28 UTC, mkholjuraev commented on src/SmartComponents/CompliancePolicies/CompliancePolicies.js
> -          benchmark {
This query is used to populate the compliance table, but I did not find any place these benchmark fields are used. I have verified this with @vkrizan.

2022-08-26 11:30 UTC, mkholjuraev commented on src/SmartComponents/ReportDownload/constants.js
> +            benchmark {
Yeap, this is PDF reporting. While I was investigated after your PR review, I do think that this also can be removed as reports are being downloaded even if I remove this `ssgVersion` field. But I have not removed it since I have no proof.

2022-08-30 08:57 UTC, skateman commented on src/SmartComponents/SystemsTable/constants.js
> +            benchmark {
Checked, seems okay to me :+1:

2022-08-30 08:59 UTC, skateman commented on src/SmartComponents/ReportDownload/constants.js
> +            benchmark {
Performance is okay :+1:

2022-08-30 09:01 UTC, skateman approved these changes
![The Seal of Approval](http://www.skateman.eu/seal.jpg)
Can someone from @RedHatInsights/team-interact also take a look?

2022-08-30 20:19 UTC, mkholjuraev commented
@skateman I think that our team is busy with their tasks. Can I merge this?

2022-08-31 06:25 UTC, skateman commented
I'd really like someone from FE to take a look before getting it in.

2022-08-31 07:20 UTC, bastilian commented on src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
> +  console.log(tabsData);
Debugging remnant? :)

2022-08-31 07:38 UTC, bastilian commented
The unsupported systems are missing a bit, there should be two versions in each row. I think it's just missing the adjustments in the `UnsupportedSystemsTable` component to get the version:

<img width="881" alt="Screenshot 2022-08-31 at 09 33 03" src="https://user-images.githubusercontent.com/7757/187620244-a2c5403f-3c70-4497-9a9a-ec8cb4c98cf6.png">

2022-08-31 16:43 UTC, mkholjuraev commented
@bastilian the issue is fixed. There was one line of code in UnsupportedSystemsTable component where I tried reading benchmark.ssgVersion.

2022-09-01 07:14 UTC, bastilian approved these changes
Awesome! Thank you @mkholjuraev!

2022-09-01 08:39 UTC, mkholjuraev commented
@skateman @bastilian merging if there is not any objection.

2022-09-01 09:40 UTC, merged