perf(GQL): RHICOMPL-3042 use GQL fragments in systems table
RedHatInsights/compliance-frontend pull request #1745
Opened 2022-08-25 12:52 UTC by xmicha82

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2022-09-02 11:31 UTC, bastilian commented on src/SmartComponents/SystemsTable/Columns.js
> +// this is not used anywhere, can it be removed?
Kick it. :)

2022-09-07 13:20 UTC, romanblanco requested changes
@xmicha82 constants `GET_SYSTEMS_WITH_REPORTS` and `GET_SYSTEMS_WITH_POLICIES` do not seem to be used after these changes. Can they be removed from `src/SmartComponents/SystemsTable/constants.js`?

2022-09-07 13:53 UTC, bastilian commented on src/SmartComponents/SystemsTable/SystemsTable.js
> +const constructQuery = (columns) => {
This function would make sense to move to a/the helpers file and also deserve a basic test with some random columns.

2022-09-07 14:27 UTC, skateman commented on src/SmartComponents/SystemsTable/SystemsTable.js
> +const constructQuery = (columns) => {
Just a noob question, wouldn't be faster to just build a string without these fragments? So the decision logic of what's requested is actually on a single location (here)?

2022-09-08 08:41 UTC, bastilian commented on src/SmartComponents/SystemsTable/SystemsTable.js
> +const constructQuery = (columns) => {
@skateman Maybe, but it might make other things difficult for/with Apollo/GraphQL.

2022-09-08 11:49 UTC, bastilian commented
This is awesome @xmicha82! Nice job! The only issue I found is on the report details page. where it appears to be missing the SSG version, but it might just be a wiring issue:

<img width="1060" alt="Screenshot 2022-09-08 at 13 45 55" src="https://user-images.githubusercontent.com/7757/189114707-f8054cdc-9ba6-4c51-ad8e-96644b5af731.png">

2022-09-14 07:43 UTC, xmicha82 commented on src/SmartComponents/SystemsTable/SystemsTable.js
> +    fragments,
`fragments` is the object with information which fragments to use, it is spread in the `variables` object

2022-09-14 11:48 UTC, bastilian commented on src/SmartComponents/SystemsTable/Cells.js
> +          ssgVersion={profile?.ssgVersion}
I think, it should rather be the query/fragment that should change, since this was recently changed to be `benchmark.version` to be easier on the backend.

2022-09-14 13:00 UTC, xmicha82 commented
@bastilian hey, i've hopefully addressed all your requests, could you please have a look? david is breating on my neck to finally have it done 😄

2022-09-14 14:06 UTC, bastilian approved these changes
Awesome! Fantastic job! Thank you @xmicha82!

2022-09-14 14:13 UTC, romanblanco approved these changes

2022-09-14 14:14 UTC, merged