RHICOMPL 3212: Rules table
RedHatInsights/compliance-frontend pull request #1788
Opened 2022-10-19 19:55 UTC by adonispuente

This implements https://issues.redhat.com/browse/RHICOMPL-3212 

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-10-19 21:17 UTC, adonispuente commented on src/PresentationalComponents/RulesTable/RulesTable.js
> +  const manageColumnsEnabled = !removeColumnDropdown
oh nice, ill send that up now

2022-10-19 22:09 UTC, bastilian commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +            options={{ pagination: false }}
... i'm sorry, but i only realised this now. We can do `options={{ pagination: false, manageColumns: false }}` and avoid adding a custom prop to the rules table entirely.

2022-10-20 13:03 UTC, xmicha82 requested changes
could you please tidy up the structure so the components are in the correct place?
please move `ViewAffectedLink.js` to `PresentationalComponents/ViewAffectedLink/ViewAffectedLink.js` and `PolicyRules` to `PresentationalComponents/PolicyRules`

2022-10-20 13:05 UTC, xmicha82 commented
also, in the mocks it says the rules view should open in a new browser window. [This](https://stackoverflow.com/questions/47574490/open-a-component-in-new-window-on-a-click-in-react) can be helpful i believe

2022-10-20 14:18 UTC, adonispuente commented
> 
Good catch, I didnt see that! I would prefer to just add the target="_blank" attribute to the Link component

2022-10-20 14:23 UTC, adonispuente commented
> another thing: i would prefer to have some kind of loading placeholder while the rules load. This shows up while the rules are loading (which is not insignificant time, since there are a lot of rules) ![Screenshot from 2022-10-20 15-17-11](https://user-images.githubusercontent.com/62351699/196959360-c0dc0142-f0ae-4f2e-9594-fee855672b85.png) and there is no sign that anything is loading.

Good point, I dont see a mock, but I could replace the words with a spinner icon as it loads, and have the table just not show up until theres data to use

2022-10-20 15:08 UTC, adonispuente commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +            options={{ pagination: false }}
When implementing I see that you need to have  ` manageColumns: true,` inside the main rulesTable to still display the 3 dots dropdown. Then when adding `options={{ pagination: false, manageColumns: false }}`, it wont 'override' it

2022-10-21 09:25 UTC, bastilian commented on src/PresentationalComponents/PolicyRules/PolicyRules.js
> +import React from 'react';
This qualifies in my opinion as a "SmartComponent".

2022-10-21 09:28 UTC, bastilian commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +            options={{ pagination: false }}
You'll need to remove what you added to the RulesTable for manageColumns here: https://github.com/RedHatInsights/compliance-frontend/pull/1788/files#diff-4216fa7cd062592b6adaf89dd868e009c72ef7d3359e5b626dd4e05cf1b6a8fdR89

The options are passed down as options for the TableTools and enable the manage columns.

2022-10-21 09:32 UTC, bastilian commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +                <ViewAffectedLink message={VIEW_POLICY_RULES} policy={policy} />
The text that `VIEW_POLICY_RULES` returns won't probably be used anywhere else but here. I'd just put the string straight in here, or even directly into the ViewAffectedLink, if we are only using the component with the same text.

2022-10-21 09:32 UTC, bastilian commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +            {hash !== '#rules' && (
I'm not sure I understand why this is necessary.

2022-10-21 09:34 UTC, bastilian commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +                <ViewAffectedLink message={VIEW_POLICY_RULES} policy={policy} />
Also, in the final version of this feature the link should only show up in the Wizard, maybe we can look for a way when we add the link there to solve this differently and not have this in ProfileTabContent directly, but passed in from higher up.

2022-10-21 18:46 UTC, adonispuente commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +            {hash !== '#rules' && (
Theres multiple rule table instances, I didnt want to add the 'view affected link' component to the policy details rule page

2022-10-21 19:23 UTC, bastilian commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +            {hash !== '#rules' && (
hm. And why use a URL hash? and not a prop or something?

2022-10-21 19:25 UTC, bastilian commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +            {hash !== '#rules' && (
We have to be careful with this, because compliance uses the URL anchor on some pages to identify the current tab.

2022-10-21 19:29 UTC, bastilian commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +                <ViewAffectedLink message={VIEW_POLICY_RULES} policy={policy} />
We should definitely look into providing that link differently into here. The passing down of the `policy` object looks also a bit iffy. I think for 3212 this link is not needed yet, so we could leave it out and as long as the page is viewable somehow it should good to merge.

2022-10-21 19:38 UTC, adonispuente commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +                <ViewAffectedLink message={VIEW_POLICY_RULES} policy={policy} />
hmm alright, ill look into adding it in, in another PR. Ill remove it from this one

2022-10-21 19:56 UTC, adonispuente commented on src/constants.js
> +  manageColumns: true,
I kept this in since it just makes it cleaner

2022-10-21 19:57 UTC, bastilian commented on src/PresentationalComponents/TabbedRules/ProfileTabContent.js
> +                <ViewAffectedLink message={VIEW_POLICY_RULES} policy={policy} />
Yeah, I think we should think about what feature would we need to add to TabbedRules/RulesTable to be able and use it for adding a link here. The final version of this feature should also, i believe, offer a way of resetting the rule selection in the rules table next to the link, so it can't be something like a "ViewAffectedLink" feature, but more a "put any content here" feature.

2022-10-21 20:01 UTC, adonispuente commented
When merging I will update the commit message

2022-10-24 09:54 UTC, bastilian commented on src/PresentationalComponents/CheckboxGroup/__snapshots__/CheckboxGroup.test.js.snap
> +    isRequired={false}
There is something fishy here. When running `rm -rf node_modules && npm install && npm run test -- -u` it'll revert these changes.

The issue is not yet visible on Travis CI, because the commit message linting is blocking the actual tests to run.

2022-10-24 09:55 UTC, bastilian commented
@adonispuente I'm afraid, you'll have to fix up the messages before we can merge this, because the actual tests are not run.

2022-10-25 09:17 UTC, bastilian commented on src/Routes.js
> +    path: '/policies/:policy_id/default_ruleset',
Minor detail, but we can change this also in the link PR. The first part should be `/scappolicies/` to align with the other policy routes.

2022-10-25 09:20 UTC, bastilian commented on src/Routes.js
> +    path: '/policies/:policy_id/default_ruleset',
We'll also need to find a way to render this page "chromeless", or check with UX if that is important.

2022-10-25 09:21 UTC, bastilian approved these changes
Nice job! LGTM! Thank you @adonispuente!

2022-10-25 09:24 UTC, bastilian commented
@xmicha82 Mind taking another look as well and give your approval.

2022-10-26 08:09 UTC, xmicha82 approved these changes
LGTM, thx @adonispuente

2022-10-26 13:45 UTC, merged