feat(cypress): add cypress to the compliance
RedHatInsights/compliance-frontend pull request #1852
Opened 2022-12-20 18:06 UTC by Fewwy

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist
Adding cypress testing library to the project. So anyone could write cypress tests when they need to
## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-12-20 21:22 UTC, mkholjuraev commented on src/SmartComponents/Reports/Reports.cy.js
> +    cy.get('table').should('have.length', 1);
I think we can improve this test by checking if there is an empty state component as well inside the table. Now the test only verifies if there is a table.

2022-12-20 21:22 UTC, mkholjuraev commented on package.json
> +    "@patternfly/patternfly": "^4.222.4",
Should not this be installed as a dev-dependency?

2022-12-21 11:05 UTC, Fewwy commented on package.json
> +    "@patternfly/patternfly": "^4.222.4",
Good catch, thanks will do that

2022-12-22 15:27 UTC, gkarat reviewed
Can we also integrate cypress to code coverage within this PR already? :-)

2023-01-09 10:03 UTC, gkarat requested changes

2023-01-09 10:03 UTC, gkarat commented on package.json
> +      "src/Utilities"
Is there a reason to omit other files under `src`? Can we use just:
```suggestion
      "src/**/*"
```

2023-01-09 10:03 UTC, gkarat commented on package.json
> +      "src/**/*.spec.ct.js",
This will exclude all cypress test files from coverage 🤔 we should remove this entry
```suggestion
```

2023-01-10 12:46 UTC, closed without merging