feat(essntl-3718): host groups integration
RedHatInsights/compliance-frontend pull request #1965
Opened 2023-07-14 00:49 UTC by Fewwy

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-07-25 10:23 UTC, gkarat requested changes
The filter works fine, and I see the parameter added to API requests. However, the response is not affected by this parameter, and the column is always N/A. Let's make sure we at least hide everything groups-related with the disabled feature flag. And then, either within this PR or another, make sure we propagate the group information for each host to appropriate column.

2023-07-25 10:23 UTC, gkarat commented on src/SmartComponents/SystemsTable/Columns.js
> +    width: 20,
Do we really need to set this width? Looks better without :)

![image](https://github.com/RedHatInsights/compliance-frontend/assets/31385370/2069c170-3cee-4006-9960-6b19eb808ff2)

2023-07-25 10:23 UTC, gkarat commented on src/SmartComponents/ComplianceSystems/ComplianceSystems.js
> +                  Columns.Groups,
I can see that with the feature flag disabled, the column will persist.

![image](https://github.com/RedHatInsights/compliance-frontend/assets/31385370/06b30603-8a3e-4b7e-9fe6-5fe2ee1b7381)

I am also afraid this will behave the same way for all other places you added this column (as I see from your PR). We have to hide the column if the feature flag is set to false.

2023-08-28 17:36 UTC, gkarat commented
Not yet ready for review

2023-08-29 09:59 UTC, bastilian commented on src/SmartComponents/SystemsTable/hooks.js
> +    let filter = cloneDeep(variables.filter);
The filter string should already be fully compiled at this point, or?

2023-08-29 10:34 UTC, gkarat commented
/retest

2023-08-29 10:54 UTC, bastilian commented on src/SmartComponents/SystemsTable/hooks.js
> +    let filter = cloneDeep(variables.filter);
... Should have marked the whole section. :D I meant that this here shouldn't be necessary. Assembling the filter should happen before the fetch function is called.

2023-08-29 10:54 UTC, Fewwy reviewed
LGTM

2023-08-29 10:54 UTC, Fewwy reviewed
LGTM

2023-08-29 11:02 UTC, gkarat commented on src/SmartComponents/SystemsTable/hooks.js
> +    let filter = cloneDeep(variables.filter);
@bastilian, I am not really sure how to do that since the inventory filter values come separately from the compliance filters. So far useGetEntities -> buildApiFilters is the only place where I can catch the inventory filters and then merge it with the compliance ones together (within `filter`).

I do see the proper way is to refactor the current `useSystemsFilter` but it will take me way more time... Perhaps we can put it as TODO item in the code? How do you feel about this solution?

2023-08-29 11:18 UTC, bastilian commented on src/SmartComponents/SystemsTable/hooks.js
> +    let filter = cloneDeep(variables.filter);
"useGetEntities -> buildApiFilters" should be the only place where it is needed to combine the filters. So, I'm confused why we need it here too.

2023-08-29 12:13 UTC, gkarat commented on src/SmartComponents/SystemsTable/hooks.js
> +    let filter = cloneDeep(variables.filter);
How you will get the inventory filters before passing it to useSystemsFilter? Selectors?

2023-08-30 09:53 UTC, LightOfHeaven1994 commented
/retest

2023-08-30 10:09 UTC, gkarat approved these changes

2023-08-30 10:13 UTC, merged