chore: Refactor SmartComponent tests to testing-library
RedHatInsights/compliance-frontend pull request #2026
Opened 2024-01-24 21:49 UTC by bastilian

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-02-06 13:16 UTC, bastilian commented
/retest

2024-02-07 10:53 UTC, gkarat commented on .eslintrc.yml
>    expect: true
Most probably, we can safely remove the jest global variables from this list since the FEC eslint config already sets "jest" environment to true https://github.com/RedHatInsights/frontend-components/blob/master/packages/eslint-config/index.js#L12

2024-02-07 10:53 UTC, gkarat commented on src/SmartComponents/CreatePolicy/CreatePolicy.test.js
> +    // TODO Replace with proper data and extend tests
Would be nice to have tests checking the wizard steps as well (the previous tests covered this) so that we don't decrease the coverage.

2024-02-07 10:53 UTC, gkarat commented on src/SmartComponents/CreatePolicy/CreateSCAPPolicy.test.js
>    it('should render benchmarks and no policies until one is selected', () => {
This test doesn't check if benchmarks are rendered

2024-02-07 10:53 UTC, gkarat commented on src/SmartComponents/CreatePolicy/FinishedCreatePolicy.test.js
>  });
Do we want to retain the error state test? Looks like this scenario was removed

2024-02-07 10:53 UTC, gkarat commented on src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.test.js
> +    ).toBeInTheDocument();
The same question here as to loading and error states

2024-02-07 10:53 UTC, gkarat commented on src/SmartComponents/EditPolicy/EditPolicySystemsTab.test.js
> -    newRuleTabs: false,
Is it deprecated? Should we stop testing this prop?

2024-02-07 10:53 UTC, gkarat commented on src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap
> +    /* istanbul ignore next */
Woah, is it expected?

2024-02-07 11:02 UTC, bastilian commented on src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap
> +    /* istanbul ignore next */
Nah, I think this should be cleaned up in a later commit.

2024-02-07 11:13 UTC, gkarat commented on src/SmartComponents/SystemDetails/SystemDetails.test.js
>    });
Can we keep these tests (especially, with the error scenario)? Or you think it's not relevant/necessary?

2024-02-07 11:13 UTC, gkarat commented on src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap
> +    /* istanbul ignore next */
yeah, I commented on outdated code, sorry :D

2024-03-21 13:21 UTC, gkarat requested changes
- Can we check `/src/PresentationalComponents/ComplianceScore/ComplianceScore.js`, `/src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js`, `/src/SmartComponents/ReportDetails/Components/ChartLegend.js` and probably other modules where we don't wrap icons with PF's `Icon` component: if the icons there keep the expected color and size?
- It looks like `/src/PresentationalComponents/ProfileThresholdField/ProfileThresholdField.js`FormGroup helper text was not changed to utilise FormHelperText. The helperText is deprecated
- In `/src/SmartComponents/CreatePolicy/EditPolicyDetails.js`, `onChange` property for `TextInput` most probably was not updated (the function now received an event object as a first argument for the callback). This results in a bug that I no longer can edit policy details.

2024-03-21 13:21 UTC, gkarat commented on src/SmartComponents/Reports/Reports.js
Please update props for SkeletonTable: they were updated and none of the current props is registered in the component interface

2024-03-21 13:26 UTC, gkarat reviewed
I am not sure if the bug was introduced by the recent migration changes, but the selection box doesn't show selected items number on any of the views in Compliance.

https://github.com/RedHatInsights/compliance-frontend/assets/31385370/f45111ad-0b7a-4aa5-bddc-65703315b2dc

2024-04-25 14:20 UTC, adonispuente commented
Overall functionality doesnt seem to be affected. Its just some small ux things.

There are very few ux things I wanted to point out for future refinement tickets (these can already we known though).

- The empty state on pf5 version has a much smaller logo (all components in general are a little smaller. This just might be a pf5 css thing though)
- The business objective section in policy details page has 2 bullet points instead of 1

2024-04-25 14:37 UTC, adonispuente approved these changes
Left a few super small nitpicks, when testing against master I couldnt find and functionality broken changes. Just small ux stuff that I believe we're already aware of. Great job overall, LGTM!

2024-04-25 14:37 UTC, adonispuente commented on src/PresentationalComponents/RulesTable/components/SeverityIcons.js
> +import React from 'react';
Nice refactor

2024-04-25 14:37 UTC, adonispuente commented on src/PresentationalComponents/index.js
> +// export {
why comment this out instead of delete?

2024-04-25 14:37 UTC, adonispuente commented on src/SmartComponents/DeletePolicy/DeletePolicy.js
> +            onChange={(_event, val) => setDeleteEnabled(val)}
also small nitpick, better for this to be consistent with your other onChange functions `{(_,v)}`

2024-04-29 10:28 UTC, bastilian commented on src/PresentationalComponents/index.js
> +// export {
Removed it.

2024-04-29 10:29 UTC, bastilian commented on src/SmartComponents/DeletePolicy/DeletePolicy.js
> +            onChange={(_event, val) => setDeleteEnabled(val)}
Changed it.

2024-04-29 10:48 UTC, bastilian commented
@gkarat:

> Can we check /src/PresentationalComponents/ComplianceScore/ComplianceScore.js, /src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js, /src/SmartComponents/ReportDetails/Components/ChartLegend.js and probably other modules where we don't wrap icons with PF's Icon component: if the icons there keep the expected color and size?

I changed the icons and wrapped them in `Icon` components and made sure they still retain the same (or very close) colour and size. In some cases for example the empty state there seem to be issues still and we need to follow up on those.

> It looks like /src/PresentationalComponents/ProfileThresholdField/ProfileThresholdField.jsFormGroup helper text was not changed to utilise FormHelperText. The helperText is deprecated

Updated to use the PF5 HelperText components. 

> In /src/SmartComponents/CreatePolicy/EditPolicyDetails.js, onChange property for TextInput most probably was not updated (the function now received an event object as a first argument for the callback). This results in a bug that I no longer can edit policy details.

Changed the `onChange`s. All Form components should work as expected. 

Re skipped cypress tests: I left them still skipped and will follow up on those later.

2024-04-30 12:47 UTC, adonispuente approved these changes
All of my comments have been addressed. Just Georgii's comments now,
LGTM!

2024-05-02 08:49 UTC, gkarat approved these changes
LGTM! Thanks for this huge work @bastilian. There are some open items, but almost all of them we can address in the next PRs. I am not sure I can spot anything else at the moment, the app works just fine after the update.

2024-05-02 08:49 UTC, gkarat commented on src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.js
It feels like something is odd with EditPolicyDetailsInline.js: if you navigate to policy details, you'd see the text for each field duplicated.

2024-05-02 09:30 UTC, merged