fix(SystemsTable): RHINENG-1923 fix os filtering
RedHatInsights/compliance-frontend pull request #2035
Opened 2024-02-07 11:44 UTC by xmicha82

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2024-02-14 12:44 UTC, xmicha82 commented
/retest

2024-02-14 13:06 UTC, gkarat requested changes
This seems to be not working for the systems page: when I click on the RHEL 7 major version, it 1) doesn't select all the checkbox for the 7.x minor versions, 2) includes hosts with the version RHEL 8.x in the results.

https://github.com/RedHatInsights/compliance-frontend/assets/31385370/846885de-a0b1-4fe5-9b98-8ca49309fa9a

2024-02-14 13:06 UTC, gkarat commented on src/constants.js
> +          acc[minorVersion.split('.')[1]] = toInclude;
Just a thought: we could explore https://github.com/npm/node-semver. It already provides with a lot of helpful functions like `minor`. This will change the code quite a lot, but it can make us more secure when working with versions.

@bastilian, @xmicha82, maybe you'd have some opinion around that? Or we better not to invest time in it?

2024-02-14 13:27 UTC, xmicha82 commented on src/constants.js
> +        value: `${minorVersion}.${majorVersion}`,
that is indeed right, must've messed that one up somehow

2024-02-21 10:55 UTC, bastilian commented on src/constants.js
> +          acc[minorVersion.split('.')[1]] = toInclude;
@gkarat I think for now we don't need to do anything complex. These OS version come from the SCAP Policies (not really the systems) imported into Compliance, which will probably always be for RHEL and should work here.

2024-02-27 12:52 UTC, gkarat reviewed
When filtering by OS, there is the same issue: I select RHEL 8 checkbox, but the results include systems of version 7 too (Compliance > Systems page)

This can give some hint: I can see that the GQL request doesn't contain any information about the OS. It is just blank `()` value

<img width="965" alt="image" src="https://github.com/RedHatInsights/compliance-frontend/assets/31385370/05f79b49-25f2-4aec-afb6-7cd65a749fbf">

2024-04-10 11:48 UTC, closed without merging