feat(RHINENG-13052): Migrate PolicyRules Page to v2
RedHatInsights/compliance-frontend pull request #2214
Opened 2024-10-22 01:15 UTC by adonispuente

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-10-23 16:46 UTC, bastilian commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +query PR_Profile($policyId: String!) {
This query should not change at all.

2024-10-23 16:55 UTC, bastilian commented on src/SmartComponents/PolicyRules/usePolicyRulesList.js
> +    return apiInstance.profileRules(security_guide_id, profile_id);
We should make this similar to how the other "api hooks" look, with the apiInstance things for the first argument and the parameters as the second.

2024-10-31 11:58 UTC, bastilian commented
@adonispuente Let's update the link here[0] and make sure it can show up properly when enabled.

[0] https://github.com/RedHatInsights/compliance-frontend/blob/master/src/PresentationalComponents/Tailorings/components/TabHeader.js#L47

2024-10-31 16:49 UTC, adonispuente commented
@bastilian Ive added the optional param in the routes page, and made the link render a conditional id based of v2 FF. 
I also adopted the new hook schema and sent that up.

2024-11-01 09:49 UTC, mkholjuraev commented on src/SmartComponents/PolicyRules/PolicyRules.js
>  import RulesTable from '../../PresentationalComponents/RulesTable/RulesTable';
let use relative import syntax:  
```suggestion
import RulesTable from '@/PresentationalComponents/RulesTable/RulesTable';
```

 there are other occurrences  below.

2024-11-01 09:49 UTC, mkholjuraev commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +const PolicyRulesGraphQL = ({ v2 }) => {
Super nitpick: how about using more meaningful name for this flag. For example: `apiV2` or `isRestEnabled`

2024-11-01 09:49 UTC, mkholjuraev commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +const PolicyRulesRest = ({ v2 }) => {
In general, I did not quite understand the data fetching implemented in this component. Questions to clarify:
1. Are policy rules batch fetched? If so, I would suggest to move all the logic into a separate hook and preferably to a new file. Also, using [useFetchBatched](https://github.com/RedHatInsights/frontend-components/blob/e66918a2eb86bfcdbae024e9997bb6ae60c9c8b6/packages/utils/src/useFetchBatched/useFetchBatched.ts#L6) hook would be ideal. 
2. Why not wrap this component with `TableStateProvider` here directly, instead of `PolicyRulesBase`. Because, this is solely REST related thingy and `PolicyRulesBase` does not have to deal with it.

2024-11-01 09:49 UTC, mkholjuraev commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +  if (isPageLoading || rulesTreeLoading || ruleGroupsLoading) {
Let's use [StateView](https://github.com/RedHatInsights/compliance-frontend/blob/master/src/PresentationalComponents/StateView/StateView.js#L12) component for displaying different states. Example: https://github.com/RedHatInsights/compliance-frontend/blob/master/src/SmartComponents/CompliancePolicies/CompliancePolicies.js#L57

2024-11-01 09:49 UTC, mkholjuraev commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +          <TableStateProvider>
How about, passing already rendered components (RulesTableRest, RulesTable) into `PolicyRulesBase`, instead of rendering them with correct props here? With this, you would not have to pass many props as those props would have already be rendered in corresponding components. You could also use [GatedComponents.js](https://github.com/RedHatInsights/compliance-frontend/blob/19faaef241abaf125a778dc02ed36820b672e093/src/PresentationalComponents/GatedComponents.js#L6) to avoid passing feature flag.

2024-11-01 09:49 UTC, mkholjuraev commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +  const apiV2Enabled = useAPIV2FeatureFlag();
Here also, we could use `GatedComponents`

2024-11-01 14:46 UTC, adonispuente commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +const PolicyRulesRest = ({ v2 }) => {
for 1. I grabbed the batching set up from https://github.com/RedHatInsights/compliance-frontend/blob/21825e634bba097eac8f96109713a4c8ce56bca6/src/PresentationalComponents/Tailorings/hooks/useSecurityGuideData.js#L27. Ill try to move it to a seperate file. Also, it looks like compliance has its own [useFetchBatched](https://github.com/RedHatInsights/compliance-frontend/blob/21825e634bba097eac8f96109713a4c8ce56bca6/src/SmartComponents/SystemsTable/hooks.js#L71),  though it looks like the same thing, Should we just delete the compliance one all together? 

Ill attempt to use the suggested version of batching though

2. Good point, done

2024-11-01 16:22 UTC, adonispuente commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +const PolicyRulesRest = ({ v2 }) => {
Ive opted to go with the implementation there, but removed the redundant useEffect logic

2024-11-05 18:00 UTC, adonispuente commented
/retest

2024-11-06 11:04 UTC, mkholjuraev commented
Thank you @adonispuente . Some issues I see:
1. export button is missing
2. both Name and Severity filters do not work
3. Somehow when I dive into tree view and select  'system settings => Selinux =>  third row (near caret icon)', I get 'valueDefinitions is undefined' error and page breaks
4. Somehow, all of the last tree level has empty cells and unknown, manual values rendered. I think it is wrong.
<img width="397" alt="image" src="https://github.com/user-attachments/assets/56f6daa8-2217-41a5-af8c-73184ce99afd">

2024-11-07 10:02 UTC, LightOfHeaven1994 commented
Additionally to @mkholjuraev comments, sorting doesn't work too. Maybe we can fix rule tree issues later as I think Sebastian was working on enabling it and then it will be easy to have working rule tree. But it's up to you

2024-11-08 14:49 UTC, mkholjuraev requested changes
I still see some of the issues:

1. both Name and Severity filters do not work yet and applying a filter suddenly changes to table view from tree view.
2. Somehow when I dive into tree view and select 'system settings => Selinux => third row (near caret icon)', now I get empty description cell view.
3. Somehow still , all of the last tree level has empty cells and unknown, manual values rendered. I think it is wrong.

2024-11-09 02:02 UTC, adonispuente commented
@mkholjuraev Sorry, I should have mentioned the issues inside another comment instead of udpating the post, youre correct. Currently the filters should work though, its just they only work with the original 10 items requested. (no longer fetching all rules). Sorting doesnt work well either but thats how it is in RulesRest everywhere. the 'Leaves' and 'twigs' are always empty arrays now and i am also investigating that

2024-11-12 20:55 UTC, bastilian commented on src/SmartComponents/PolicyRules/PolicyRules.js
> +          component={
Maybe this can use `children`. Same below. https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children

2024-11-21 09:48 UTC, LightOfHeaven1994 approved these changes
I took a look and generally looks good. We are getting closer to the release and I don't want to hold it more. There are couple things that can be fixed later:

1. Sorting (but it was an issue before with GQL)
2. Table tree reloads after opening each node
3. If I use search by name + expand some rules - page crashes (Search by "Sel", find rule "Configure SELinux Policy" and try to expand it) -  I will create a separate jira to track this

2024-11-21 11:33 UTC, merged