feat(RHINENG-13842): Change rule tree icon
RedHatInsights/compliance-frontend pull request #2225
Opened 2024-10-24 14:00 UTC by LightOfHeaven1994

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-10-24 15:32 UTC, bastilian commented on src/Frameworks/AsyncTableTools/components/TreeIcon.js
> +    src={require('../../../../static/images/pf-icon-tree-view.svg')}
Is it not in PF icons?

2024-10-24 17:55 UTC, johnsonm325 requested changes
Remove those TreeIcon files, the svg file, and just import TreeIcon from patternfly icons.

2024-10-24 17:55 UTC, johnsonm325 commented on src/Frameworks/AsyncTableTools/hooks/useTableView/views/index.js
> +import TreeIcon from '../../../components/TreeIcon';
Agree with @bastilian, Replace the TreeIcon file and use `import { TreeIcon } from '@patternfly/react-icons';`.

2024-10-24 22:22 UTC, LightOfHeaven1994 commented on src/Frameworks/AsyncTableTools/hooks/useTableView/views/index.js
> +import TreeIcon from '../../../components/TreeIcon';
@johnsonm325 @bastilian I wasn't able to find tree icon [here](https://www.patternfly.org/design-foundations/icons/) . I tried to paste the thing you suggested and see Christmas tree :smile: 
![image](https://github.com/user-attachments/assets/5d41873a-072f-4286-8a13-5cb62b7a3715)

2024-10-24 22:22 UTC, LightOfHeaven1994 commented on src/Frameworks/AsyncTableTools/hooks/useTableView/views/index.js
> +import TreeIcon from '../../../components/TreeIcon';
I think that's the reason why UXD had this icon saved in some google shared folder as there are no such icon on pf side

2024-10-25 09:19 UTC, LightOfHeaven1994 commented on src/Frameworks/AsyncTableTools/components/TreeIcon.js
> +    src={require('../../../../static/images/pf-icon-tree-view.svg')}
found it, had to take a look into code and found a link to all available icons https://react-staging.patternfly.org/icons/

2024-10-25 09:20 UTC, LightOfHeaven1994 commented on src/Frameworks/AsyncTableTools/hooks/useTableView/views/index.js
> +import TreeIcon from '../../../components/TreeIcon';
@johnsonm325 good catch, found correct icon here found it, had to take a look into code and found a link to all available icons https://react-staging.patternfly.org/icons/

2024-10-25 09:25 UTC, mkholjuraev commented on src/Frameworks/AsyncTableTools/hooks/useTableView/views/index.js
> +import TreeIcon from '../../../components/TreeIcon';
Christmas is coming :)

2024-10-25 14:02 UTC, johnsonm325 approved these changes

2024-10-25 15:57 UTC, johnsonm325 commented
/retest

2024-10-25 17:30 UTC, merged