fix(ReportDetails): RHICOMPL-1138 Show hosts with policy results
RedHatInsights/compliance-frontend pull request #865
Opened 2020-12-09 05:21 UTC by akofink

This changes the systems table to accept a defaultFilter prop which will
be added to user filters during the API request. This is to allow
specifying a new filter for the ReportDetails page to only show hosts
that have test results for a given policy (a set of profiles associated
to the policy). The new filter takes policy ID or any profile ID
associated to the policy.

Requires https://github.com/RedHatInsights/compliance-backend/pull/678

Signed-off-by: Andrew Kofink <akofink@redhat.com>

2020-12-09 09:21 UTC, bastilian commented on src/SmartComponents/SystemsTable/SystemsTable.js
> -            filter = `policy_id = ${policyId} and ${filter}`;
Do we not want need to use this filter anymore?

2020-12-09 13:36 UTC, vkrizan requested changes

2020-12-09 13:36 UTC, vkrizan commented on src/SmartComponents/SystemsTable/SystemsTable.js
> -            filter = `policy_id = ${policyId} and ${filter}`;
Indeed. This affects showing assigned-only systems on a SCAP Policy. Mind to adding a default filter for that case (`PolicyDetails`). Also please check other usages, like policy edit.

2020-12-09 13:36 UTC, vkrizan commented
Works correctly on the reports page. Thanks.

2020-12-09 16:36 UTC, akofink commented on src/SmartComponents/SystemsTable/SystemsTable.js
> -            filter = `policy_id = ${policyId} and ${filter}`;
Whoops! Sorry, I meant to check for this and forgot :see_no_evil: Updated!

2020-12-10 09:14 UTC, vkrizan approved these changes
Seems to work on all pages. Thank you.

2020-12-10 14:02 UTC, merged