Migrate webpack 5
RedHatInsights/compliance-frontend pull request #924
Opened 2021-01-12 09:02 UTC by Hyperkid123

### Changes
- migrate compliance to crc common webpack config
  - update to webpack 5
  - prepare compliance UI form chrome 2.0
- update react and react-dom dependencies
  - no breaking changes
  - required to unify react-test-renderer and react-dom
- use new Inventory component system
  - No longer uses window function but react component from FEC. This inventory is ready for chrome 2.0
- changed imports to use ESM modules instead of UMD
  -  reduces the overall build size by 2 MB (there is still some room for improvement but we need chrome 2.0 first)

@vkrizan @bastilian Can you please double-check the UI if nothing is broken? Custom CSS in particular.

2021-01-12 09:49 UTC, Hyperkid123 commented
We have found one more bug with global filter which is supposed to be disabled but the filter still adds some data to the URL hash.

2021-01-13 13:36 UTC, akofink reviewed
Thank you, @Hyperkid123! It seems to work as expected, though it's a very large change. I'd like at least a second reviewer and ideally @bastilian who is out until tomorrow.

2021-01-13 13:52 UTC, Hyperkid123 commented
@akofink ofc. Take as much time as you need. We need to make sure it works properly.

2021-01-18 16:25 UTC, bastilian commented on config/dev.webpack.config.js
> -    port: process.env.FRONTEND_PORT ? process.env.FRONTEND_PORT  : '8002',
We will need this still for the docker-compose setup to work. I put it locally into `devserverConfig` which seems to be a good place to put this.

2021-01-18 16:26 UTC, bastilian commented on src/SmartComponents/SystemsTable/SystemsTable.js
> +            return this.props.updateSystems({
Just a nitpick. :) Does this need an explicit return?

2021-01-18 16:31 UTC, bastilian approved these changes
Thank you @Hyperkid123! This really great!

Everything appears to be working correctly even with and without the `inventory-compliance` package linked.

There are two minor things, but we can address those later on as well.

2021-01-19 08:00 UTC, Hyperkid123 commented on config/dev.webpack.config.js
> -    port: process.env.FRONTEND_PORT ? process.env.FRONTEND_PORT  : '8002',
Yeah, that is exactly why I have created the file. And then just forgot to add the config :smile:

2021-01-19 09:54 UTC, bastilian requested changes

2021-01-19 09:54 UTC, bastilian commented on src/App.js
> +        localStorage.setItem(`${LOCAL_STORE_FEATURE_PREFIX}:newInventory`, true);
Oh, I almost missed that. This is not good, we can not yet enable the new Inventory implementation.

2021-01-19 10:08 UTC, Hyperkid123 commented on src/App.js
> +        localStorage.setItem(`${LOCAL_STORE_FEATURE_PREFIX}:newInventory`, true);
Is there any specific reason? The old implementation causes some issues in the UI. It actually does not load the data and it's tuck in the loading state.

2021-01-19 10:15 UTC, bastilian commented on src/App.js
> +        localStorage.setItem(`${LOCAL_STORE_FEATURE_PREFIX}:newInventory`, true);
@Hyperkid123 Yeah, the new implementation removes a few things we need before we can switch to not introduce regressions.

The issue you are referring to may be one that we are already aware of and it is marked to be resolved with moving over to the new implementation, but it is not a persistent bug and is resolved most of the times with a refresh.

I just tested it with removing this line and disabling the newInventory and all works as expected.

2021-01-19 10:18 UTC, Hyperkid123 commented on src/App.js
> +        localStorage.setItem(`${LOCAL_STORE_FEATURE_PREFIX}:newInventory`, true);
Ah ok. I was under the impression the migration caused the issue! Alright. I will remove it then

2021-01-19 10:20 UTC, bastilian commented on src/App.js
> +        localStorage.setItem(`${LOCAL_STORE_FEATURE_PREFIX}:newInventory`, true);
Awesome! Thank you! The old implementation is buggy... :D

2021-01-19 11:47 UTC, bastilian approved these changes
Looks all good now! Thank you again @Hyperkid123! Awesome work!

2021-01-19 11:48 UTC, merged

2021-01-19 11:55 UTC, Hyperkid123 commented
NP. Let me know if any issues surface.