[WIP]Added ouiaid attributes to all UI components
RedHatInsights/compliance-frontend pull request #926
Opened 2021-01-13 11:05 UTC by mayurilahane

2021-01-13 18:07 UTC, akofink approved these changes
Wow, awesome! Thanks, @mayurilahane! @Victoremepunto check it out :)

I'd also like @bastilian's sign off on this one before we merge.

2021-03-11 19:27 UTC, akofink commented
@bastilian could you please take a look?

2021-03-12 10:22 UTC, bastilian commented
@mayurilahane Is this still "WIP"? 

@Victoremepunto & @LightOfHeaven1994 could you also to weigh in and make sure the IDs are useful for IQE tests?

2021-03-12 11:31 UTC, mayurilahane commented
Hey, @bastilian thanks for reminding me.
I just updated it! :)

2021-04-01 11:53 UTC, LightOfHeaven1994 requested changes
PR looks good, only couple suggestions

2021-04-01 11:53 UTC, LightOfHeaven1994 commented on src/SmartComponents/PolicyDetails/PolicyDetails.js
> +                    <Breadcrumb ouiaId="policyName">
Breadcrumb is not a policy name but path to policy details (Compliance->SCAP policies, PCI-DSS....)
Maybe better name will be pathToPolicy

2021-04-01 11:53 UTC, LightOfHeaven1994 commented on src/SmartComponents/ReportDetails/ReportDetails.js
> +                <Breadcrumb ouiaId="titles">
same here, pathToReport

2021-04-01 11:53 UTC, LightOfHeaven1994 commented on src/SmartComponents/SystemDetails/SystemDetails.js
> +                <Breadcrumb ouiaId="systemName">
same here, pathToSystem

2021-04-01 11:53 UTC, LightOfHeaven1994 commented on src/SmartComponents/Reports/Reports.js
> +            ouiaId="support removed"
after you rebase PR it should disappear

2021-04-17 19:15 UTC, sthirugn commented
@mayurilahane can you please update the recommended changes when you get a chance.

2021-04-19 07:47 UTC, mayurilahane commented
Hey, @sthirugn
sorry but right now I am stuck with something urgent but I will make sure to complete these changes as early as possible!
Thanks for the reviews!

2021-05-18 09:39 UTC, bastilian commented
@mayurilahane Hej, Thank you for going over our app and adding the attributes! If you don't mind we can take it from here and rebase the PR and update it to include the changes with attributes that were introduced meanwhile.

2021-05-18 11:00 UTC, mayurilahane commented on src/SmartComponents/Reports/Reports.js
> +            ouiaId="support removed"
not sure about this.
I have rebased it!

2021-05-18 11:04 UTC, mayurilahane commented
> @mayurilahane Hej, Thank you for going over our app and adding the attributes! If you don't mind we can take it from here and rebase the PR and update it to include the changes with attributes that were introduced meanwhile.

I apologize for taking so long to update this!
please have a look at updated changes and if anything you find you can take it from there.
I really appreciate your understanding!
Thank you so much!!

2021-05-18 13:04 UTC, bastilian commented
@mayurilahane Thank you very much for the efforts! We are happy to take it from here to get these attributes in sooner for our QEs to use!

2021-05-25 16:39 UTC, vkrizan commented
@LightOfHeaven1994 @bastilian I've synced it with current code base. Would you mind having another look?

Unfortunately, I wasn't able to add the `ouiaId` to a `Tile` component. It did not recognized it.

2021-05-25 20:03 UTC, akofink approved these changes
Looks good, just one comment. I guess we can merge as is, but as soon as IQE code (or future functional/integration dev tests) are written, we'll have to be mindful of updating any of these without a related IQE update as well.

2021-05-25 20:03 UTC, akofink commented on src/PresentationalComponents/ReportsTable/ReportsTable.js
> +            ouiaId="reports"
Would it be helpful to name the actual component? Like, `reportsTable` here, or `newPolicyButton` instead of `newPolicy`. We may want to use `newPolicyModal` or `newPolicyDetails`, so more namespacing could be beneficial.

2021-05-26 08:35 UTC, vkrizan commented on src/PresentationalComponents/ReportsTable/ReportsTable.js
> +            ouiaId="reports"
@LightOfHeaven1994 @Victoremepunto ^

2021-05-26 09:53 UTC, Victoremepunto commented on src/PresentationalComponents/ReportsTable/ReportsTable.js
> +            ouiaId="reports"
yes, we should add namespacing where it makes sense, so the element can be uniquely identified. `reportsTable` seems to make sense

2021-05-26 10:05 UTC, bastilian commented on src/PresentationalComponents/ReportsTable/ReportsTable.js
> +            ouiaId="reports"
@Victoremepunto Can we define a few "Guidelines" to add to the README on what components need an identifier and what they should look like and also establish a process to verify they are properly set for new features?

2021-05-26 10:17 UTC, LightOfHeaven1994 commented on src/PresentationalComponents/ReportsTable/ReportsTable.js
> +            ouiaId="reports"
Sounds good to me, better have name+component in camelCase.

2021-05-26 10:17 UTC, vkrizan commented on src/PresentationalComponents/ReportsTable/ReportsTable.js
> +            ouiaId="reports"
I'd leave the ownership of OUIA IDs fully to QE. You can update them as needed.

2021-05-26 10:21 UTC, LightOfHeaven1994 commented on src/PresentationalComponents/ReportsTable/ReportsTable.js
> +            ouiaId="reports"
@vkrizan sure, thanks. Will do this today

2021-05-26 11:53 UTC, LightOfHeaven1994 approved these changes

2021-05-26 13:43 UTC, akofink approved these changes
Nice! It just needs a rebase.

2021-05-26 13:54 UTC, vkrizan commented
Squased and merged via commit 0d49a4acb5cfbf97b293be0e7ba1af56e7167a2d.

Thank you again @mayurilahane and @LightOfHeaven1994 !

2021-05-26 13:54 UTC, closed without merging